### ISSUE TITLE
[Question] What is the scope of decentralized block chains?

### ISSUE THREAD

**Issue by melvincarvalho** [BlockchainCommons/www.blockchaincommons.com#29]
Recently came across this project on the bitcoin-dev mailing list

I've been a big fan of decentralized identity and the various principles around it since at least 2007.  I've been looking through the work, and there is a lot to like

Question I have relates to the scope of the different block chains

I'm glad to see bitcoin block chain supported

Which other chains are considered to be decentralized enough to satisfy the blockchain commons principles.  In particular, is Ethereum considered to be a decentralized block chain wrt block chain commons

I appreciate there are an enormous number of block chains so not all can be put in buckets.  Just trying to get a feel for what's in scope, and what's out here.  Any pointers would be welcome.  Thanks!

**Comment by ChristopherA** [comment]
A lot of my input ultimately went into the beginnings of the DID Method Rubric, which also tries to examine the nature of what it means to be decentralized. I highly commend this version, and I hope to apply it back to blockchain transactional questions someday.

https://www.w3.org/TR/did-rubric/

My own hypothesis is that we will discover that, like Arrow’s Impossibility Theorem is for voting, that perfect decentralization is not possible. Some decentralized metric will be antithetical to another metric.

**Comment by melvincarvalho** [comment]
@ChristopherA you didnt answer this question:

> is Ethereum considered to be a decentralized block chain wrt block chain commons

I am assuming the answer is yes that block chain commons considers Ethereum to be sufficiently decentralized.  If so, that would be a controversial stance in the space.  And it would be good to hear the answer.
