### ISSUE TITLE
"More" button with excerpt separator in Jekyll Theme

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/www.blockchaincommons.com#6]
As per #4:

Our blog page currently shows each post up to the excerpt separator, which is what we want. However, it should also include a “more” or “read the full article” or something down at the bottom for any article whose view on this page is terminated by an excerpt separator
* See https://www.blockchaincommons.com/posts/

**Comment by shannona** [comment]
This is now possible, we just need to remember to add:
```
<div class="bold--excerpt--node">Read More</div>

<!--more-->
```
